name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager.yml
    secrets: inherit

  release:
    needs:
      - build-manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Base Tag
        id: get_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Download Final Repacked APK
        uses: actions/download-artifact@v4
        with:
          name: manager
          path: ./final-apk

      - name: List downloaded files
        run: ls -R ./final-apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.LATEST_TAG }}
          files: |
            ./final-apk/*.apk
